version: '2.3' 
services:  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
               
    ports: 
      - 5672:5672
      - 25672:25672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API 
               
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017 

  service_download:
    build:
      context: ./service/
    environment:
      - FILA_HOST_RABBITMQ=amqp://admin:admin@rabbitmq:5672
      - FILA_DOWNLOAD_IMAGE=download-image
      - FILA_DOWNLOAD_IMAGE_RECEIVE_COUNT=download-image-receive-count
      - FILA_DOWNLOAD_IMAGE_RECEIVED=download-image-received
      - MONGODB=mongodb://mongodb_container/pbx-desafio
    depends_on:
      - "rabbitmq"   
      - "mongodb_container"    
    ports:
      - "3004:3004"
    links:
      - rabbitmq:rabbitmq
      - mongodb_container:mongodb_container